sudo: required

services:
  - docker

language: go

go:
  - 1.8.x

install: 
    - make get-deps

after_success:
  - ls -lah build/*
  - docker images
  - docker run -d -p 8076:8076 temperature-server
  - DID=`docker ps -a | grep "temperature-server" |  awk '{ print $1 }'`
  - echo $DID
  - docker logs -t $DID
  - sleep 15
  - curl http://localhost:8076/temperature/convertTemperature -X POST -d '{"FromFahrenheit":false,"Temperature":32.0}'  -H 'Content-Type:application/json'


