package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/natjking/resttemp/models"
)

/*GetAvailabilityOK 200 OK

swagger:response getAvailabilityOK
*/
type GetAvailabilityOK struct {

	/*
	  In: Body
	*/
	Payload *models.AllGoodResponse `json:"body,omitempty"`
}

// NewGetAvailabilityOK creates GetAvailabilityOK with default headers values
func NewGetAvailabilityOK() *GetAvailabilityOK {
	return &GetAvailabilityOK{}
}

// WithPayload adds the payload to the get availability o k response
func (o *GetAvailabilityOK) WithPayload(payload *models.AllGoodResponse) *GetAvailabilityOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get availability o k response
func (o *GetAvailabilityOK) SetPayload(payload *models.AllGoodResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAvailabilityOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
