package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// AllGoodResponse all good response
// swagger:model AllGoodResponse
type AllGoodResponse struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this all good response
func (m *AllGoodResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
