package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Request request
// swagger:model Request
type Request struct {

	// from fahrenheit
	FromFahrenheit bool `json:"fromFahrenheit,omitempty"`

	// temperature
	Temperature float32 `json:"temperature,omitempty"`
}

// Validate validates this request
func (m *Request) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
